/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author Karoliny
 */
public class DlgJanRelatorio extends javax.swing.JDialog {

    /**
     * Creates new form FrmJanRelatorio
     */
    public DlgJanRelatorio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitulo = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        panelTotalTarefas = new javax.swing.JPanel();
        labelTotalTarefas = new javax.swing.JLabel();
        panelTarefasPendentes = new javax.swing.JPanel();
        labelTarefasComecar = new javax.swing.JLabel();
        panelTarefasEmAndamento = new javax.swing.JPanel();
        labelTarefasAndamento = new javax.swing.JLabel();
        panelTarefasConcluidas = new javax.swing.JPanel();
        labelTarefasFinalizadas = new javax.swing.JLabel();
        panelTarefaEquipe = new javax.swing.JPanel();
        labelEquipe = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnVoltarRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FocusTask - Relatórios");

        txtTitulo.setFont(new java.awt.Font("Source Sans Pro Black", 0, 24)); // NOI18N
        txtTitulo.setText("RELATÓRIOS DO SISTEMA");

        javax.swing.GroupLayout painelTituloLayout = new javax.swing.GroupLayout(painelTitulo);
        painelTitulo.setLayout(painelTituloLayout);
        painelTituloLayout.setHorizontalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTitulo)
                .addGap(197, 197, 197))
        );
        painelTituloLayout.setVerticalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtTitulo)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelTotalTarefas.setBackground(new java.awt.Color(179, 217, 255));
        panelTotalTarefas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelTotalTarefas.setForeground(new java.awt.Color(255, 255, 255));

        labelTotalTarefas.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelTotalTarefas.setText("TOTAL DE TAREFAS");

        javax.swing.GroupLayout panelTotalTarefasLayout = new javax.swing.GroupLayout(panelTotalTarefas);
        panelTotalTarefas.setLayout(panelTotalTarefasLayout);
        panelTotalTarefasLayout.setHorizontalGroup(
            panelTotalTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalTarefasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelTotalTarefas)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelTotalTarefasLayout.setVerticalGroup(
            panelTotalTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalTarefasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelTotalTarefas)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        panelTarefasPendentes.setBackground(new java.awt.Color(255, 50, 50));
        panelTarefasPendentes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTarefasComecar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelTarefasComecar.setText("A COMEÇAR");

        javax.swing.GroupLayout panelTarefasPendentesLayout = new javax.swing.GroupLayout(panelTarefasPendentes);
        panelTarefasPendentes.setLayout(panelTarefasPendentesLayout);
        panelTarefasPendentesLayout.setHorizontalGroup(
            panelTarefasPendentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarefasPendentesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelTarefasComecar)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelTarefasPendentesLayout.setVerticalGroup(
            panelTarefasPendentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarefasPendentesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelTarefasComecar)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        panelTarefasEmAndamento.setBackground(new java.awt.Color(255, 255, 69));
        panelTarefasEmAndamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTarefasAndamento.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelTarefasAndamento.setText("EM ANDAMENTO");

        javax.swing.GroupLayout panelTarefasEmAndamentoLayout = new javax.swing.GroupLayout(panelTarefasEmAndamento);
        panelTarefasEmAndamento.setLayout(panelTarefasEmAndamentoLayout);
        panelTarefasEmAndamentoLayout.setHorizontalGroup(
            panelTarefasEmAndamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTarefasEmAndamentoLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(labelTarefasAndamento)
                .addGap(29, 29, 29))
        );
        panelTarefasEmAndamentoLayout.setVerticalGroup(
            panelTarefasEmAndamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarefasEmAndamentoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelTarefasAndamento)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        panelTarefasConcluidas.setBackground(new java.awt.Color(57, 255, 106));
        panelTarefasConcluidas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTarefasFinalizadas.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelTarefasFinalizadas.setText("FINALIZADAS");

        javax.swing.GroupLayout panelTarefasConcluidasLayout = new javax.swing.GroupLayout(panelTarefasConcluidas);
        panelTarefasConcluidas.setLayout(panelTarefasConcluidasLayout);
        panelTarefasConcluidasLayout.setHorizontalGroup(
            panelTarefasConcluidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarefasConcluidasLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(labelTarefasFinalizadas)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panelTarefasConcluidasLayout.setVerticalGroup(
            panelTarefasConcluidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarefasConcluidasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelTarefasFinalizadas)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        panelTarefaEquipe.setBorder(javax.swing.BorderFactory.createTitledBorder("Tarefas por Equipe"));

        labelEquipe.setText("MARKETING");

        jLabel1.setText("Total de tarefas: 10");

        javax.swing.GroupLayout panelTarefaEquipeLayout = new javax.swing.GroupLayout(panelTarefaEquipe);
        panelTarefaEquipe.setLayout(panelTarefaEquipeLayout);
        panelTarefaEquipeLayout.setHorizontalGroup(
            panelTarefaEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarefaEquipeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTarefaEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEquipe)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTarefaEquipeLayout.setVerticalGroup(
            panelTarefaEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarefaEquipeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelEquipe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        btnVoltarRelatorio.setText("<< Voltar");
        btnVoltarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVoltarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelTarefaEquipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(panelTotalTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelTarefasPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelTarefasEmAndamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelTarefasConcluidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTotalTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTarefasPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTarefasEmAndamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTarefasConcluidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(panelTarefaEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVoltarRelatorio)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarRelatorioActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgJanRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgJanRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgJanRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgJanRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgJanRelatorio dialog = new DlgJanRelatorio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltarRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelEquipe;
    private javax.swing.JLabel labelTarefasAndamento;
    private javax.swing.JLabel labelTarefasComecar;
    private javax.swing.JLabel labelTarefasFinalizadas;
    private javax.swing.JLabel labelTotalTarefas;
    private javax.swing.JPanel painelTitulo;
    private javax.swing.JPanel panelTarefaEquipe;
    private javax.swing.JPanel panelTarefasConcluidas;
    private javax.swing.JPanel panelTarefasEmAndamento;
    private javax.swing.JPanel panelTarefasPendentes;
    private javax.swing.JPanel panelTotalTarefas;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
