package view;

import static controller.FuncoesUteis.dateToStr;
import static controller.FuncoesUteis.strToDate;
import controller.GerenciadorInterface;
import domain.Equipe;
import domain.Usuario;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Karoliny
 */
public class DlgJanUsuario extends javax.swing.JDialog {

    private Usuario usuarioSelecionado;

    public DlgJanUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        List<Equipe> lista = GerenciadorInterface.getMyInstance().getDominio().listar(Equipe.class);
        carregarComboEquipes(lista);

        btnSalvarUsuario.setEnabled(false);
        btnEditarUsuario.setEnabled(false);
        btnExcluirUsuario.setEnabled(false);

        txtNome.addActionListener(e -> verificarCampos());
        txtEmail.addActionListener(e -> verificarCampos());
        txtDataNascimento.addActionListener(e -> verificarCampos());
        txtCPF.addActionListener(e -> verificarCampos());
        txtTelefone.addActionListener(e -> verificarCampos());
        comboBoxEquipe.addActionListener(e -> verificarCampos());
        radioBtnFeminino.addActionListener(e -> verificarCampos());
        radioBtnMasculino.addActionListener(e -> verificarCampos());
        radioBtnNaoDizer.addActionListener(e -> verificarCampos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSexo = new javax.swing.ButtonGroup();
        painelTituloUsuario = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        txtDesc = new javax.swing.JLabel();
        panelUsuario = new javax.swing.JPanel();
        labelNomeUsuario = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        panelSexo = new javax.swing.JPanel();
        radioBtnFeminino = new javax.swing.JRadioButton();
        radioBtnMasculino = new javax.swing.JRadioButton();
        radioBtnNaoDizer = new javax.swing.JRadioButton();
        labelEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        labelDataNascimento = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        labelSetor = new javax.swing.JLabel();
        comboBoxEquipe = new javax.swing.JComboBox<>();
        btnSalvarUsuario = new javax.swing.JButton();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        labelCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        btnPesquisarUsuario = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnExcluirUsuario = new javax.swing.JButton();
        btnVoltarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtTitulo.setFont(new java.awt.Font("Source Sans Pro Black", 0, 24)); // NOI18N
        txtTitulo.setText("Usuários");

        txtDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDesc.setText("Cadastro de usuários");

        javax.swing.GroupLayout painelTituloUsuarioLayout = new javax.swing.GroupLayout(painelTituloUsuario);
        painelTituloUsuario.setLayout(painelTituloUsuarioLayout);
        painelTituloUsuarioLayout.setHorizontalGroup(
            painelTituloUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloUsuarioLayout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addGroup(painelTituloUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTituloUsuarioLayout.createSequentialGroup()
                        .addComponent(txtTitulo)
                        .addGap(197, 197, 197))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTituloUsuarioLayout.createSequentialGroup()
                        .addComponent(txtDesc)
                        .addGap(180, 180, 180))))
        );
        painelTituloUsuarioLayout.setVerticalGroup(
            painelTituloUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDesc)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelNomeUsuario.setText("Nome");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        panelSexo.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));

        btnGroupSexo.add(radioBtnFeminino);
        radioBtnFeminino.setText("Feminino");

        btnGroupSexo.add(radioBtnMasculino);
        radioBtnMasculino.setText("Masculino");
        radioBtnMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnMasculinoActionPerformed(evt);
            }
        });

        btnGroupSexo.add(radioBtnNaoDizer);
        radioBtnNaoDizer.setText("Prefiro não dizer");
        radioBtnNaoDizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnNaoDizerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSexoLayout = new javax.swing.GroupLayout(panelSexo);
        panelSexo.setLayout(panelSexoLayout);
        panelSexoLayout.setHorizontalGroup(
            panelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSexoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioBtnFeminino)
                    .addComponent(radioBtnMasculino)
                    .addComponent(radioBtnNaoDizer))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelSexoLayout.setVerticalGroup(
            panelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSexoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioBtnFeminino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBtnMasculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBtnNaoDizer)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        labelEmail.setText("E-mail");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        labelDataNascimento.setText("Data de nascimento");

        labelTelefone.setText("Telefone");

        labelSetor.setText("Equipe");

        comboBoxEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEquipeActionPerformed(evt);
            }
        });

        btnSalvarUsuario.setText("Salvar");
        btnSalvarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarUsuarioActionPerformed(evt);
            }
        });

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        labelCPF.setText("CPF");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnPesquisarUsuario.setText("Pesquisar");
        btnPesquisarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarUsuarioActionPerformed(evt);
            }
        });

        btnEditarUsuario.setText("Editar");
        btnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnExcluirUsuario.setText("Excluir");
        btnExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelNomeUsuario)
                            .addComponent(labelEmail)
                            .addGroup(panelUsuarioLayout.createSequentialGroup()
                                .addComponent(labelDataNascimento)
                                .addGap(44, 44, 44)
                                .addComponent(labelTelefone))
                            .addGroup(panelUsuarioLayout.createSequentialGroup()
                                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                        .addComponent(txtDataNascimento, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(labelCPF))
                                .addGap(18, 18, 18)
                                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSetor)
                                    .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(comboBoxEquipe, javax.swing.GroupLayout.Alignment.LEADING, 0, 137, Short.MAX_VALUE)
                                        .addComponent(txtTelefone))))
                            .addComponent(txtEmail)
                            .addComponent(txtNome))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarUsuario))
                        .addGap(86, 86, 86))
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addComponent(btnSalvarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelNomeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDataNascimento)
                            .addComponent(labelTelefone))
                        .addGap(6, 6, 6)
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCPF)
                            .addComponent(labelSetor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarUsuario)
                    .addComponent(btnEditarUsuario)
                    .addComponent(btnLimpar)
                    .addComponent(btnExcluirUsuario))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnVoltarUsuario.setText("<< Voltar");
        btnVoltarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVoltarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(painelTituloUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(painelTituloUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVoltarUsuario)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarUsuarioActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarUsuarioActionPerformed

    private void radioBtnMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnMasculinoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void radioBtnNaoDizerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnNaoDizerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnNaoDizerActionPerformed

    private void btnSalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarUsuarioActionPerformed
        String sexo;

        if (radioBtnMasculino.isSelected()) {
            sexo = "M";
        } else {
            sexo = "F";
        }

        try {
            GerenciadorInterface.getMyInstance().getDominio().inserirUsuario(txtNome.getText(), txtCPF.getText(),
                    txtEmail.getText(), sexo, strToDate(txtDataNascimento.getText()), txtTelefone.getText(),
                    (Equipe) comboBoxEquipe.getSelectedItem());
            JOptionPane.showMessageDialog(null, "Usuário salvo com sucesso!");
            limparCampos();
        } catch (ParseException ex) {
            Logger.getLogger(DlgJanUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSalvarUsuarioActionPerformed

    private void comboBoxEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxEquipeActionPerformed

    private void btnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuarioActionPerformed
        try {
            if (usuarioSelecionado == null) {
                JOptionPane.showMessageDialog(
                        null,
                        "Pesquise um usuário primeiro!"
                );
                return;
            }

            String sexo;

            if (radioBtnMasculino.isSelected()) {
                sexo = "M";
            } else if (radioBtnFeminino.isSelected()) {
                sexo = "F";
            } else {
                sexo = "ND";
            }

            GerenciadorInterface.getMyInstance().getDominio().alterarUsuario(usuarioSelecionado.getId(), txtNome.getText(),
                    txtCPF.getText(), txtEmail.getText(), txtTelefone.getText(), strToDate(txtDataNascimento.getText()),
                    sexo, (Equipe) comboBoxEquipe.getSelectedItem()
            );

            JOptionPane.showMessageDialog(null, "Usuário alterado com sucesso!");
            limparCampos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditarUsuarioActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPesquisarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarUsuarioActionPerformed
        try {

            Usuario usuario = GerenciadorInterface.getMyInstance().getDominio().pesquisarUsuarioPorNome(txtNome.getText());

            if (usuario == null) {
                JOptionPane.showMessageDialog(null,
                        "Usuário não encontrado!");
                return;
            }

            usuarioSelecionado = usuario;
            txtNome.setText(usuario.getNome());
            txtEmail.setText(usuario.getEmail());
            txtTelefone.setText(usuario.getTelefone());
            txtDataNascimento.setText(dateToStr(usuario.getDtNascimento()));
            txtCPF.setText(usuario.getCpf());
            comboBoxEquipe.setSelectedItem(usuario.getEquipe());
            if (usuario.getSexo().equals("M")) {
                radioBtnMasculino.setSelected(true);
            } else if (usuario.getSexo().equals("F")) {
                radioBtnFeminino.setSelected(true);
            } else if (usuario.getSexo().equals("ND")) {
                radioBtnNaoDizer.setSelected(true);
            }

            btnEditarUsuario.setEnabled(true);
            btnExcluirUsuario.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }

    }//GEN-LAST:event_btnPesquisarUsuarioActionPerformed

    private void btnExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUsuarioActionPerformed
        try {

            if (usuarioSelecionado == null) {
                JOptionPane.showMessageDialog(
                        null,
                        "Pesquise um usuário primeiro!"
                );
                return;
            }

            if (GerenciadorInterface.getMyInstance().getDominio().usuarioPossuiTarefas(usuarioSelecionado)) {
                JOptionPane.showMessageDialog(
                        null,
                        "Não é possível excluir este usuário porque ele é responsável por uma ou mais tarefas."
                );

                return;
            }

            int resposta = JOptionPane.showConfirmDialog(
                    null,
                    "Deseja realmente excluir este usuário?",
                    "Confirmação",
                    JOptionPane.YES_NO_OPTION
            );

            if (resposta == JOptionPane.YES_OPTION) {

                GerenciadorInterface.getMyInstance().getDominio().excluirUsuario(usuarioSelecionado.getId());

                JOptionPane.showMessageDialog(
                        null,
                        "Usuário excluído com sucesso!"
                );

                limparCampos();
                usuarioSelecionado = null;
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    "Erro ao excluir: " + e.getMessage()
            );
        }
    }//GEN-LAST:event_btnExcluirUsuarioActionPerformed

    private void verificarCampos() {
        boolean temNome = !txtNome.getText().trim().isEmpty();
        boolean temEmail = !txtEmail.getText().trim().isEmpty();
        boolean temDtNascimento = !txtDataNascimento.getText().trim().isEmpty();
        boolean temTelefone = !txtTelefone.getText().trim().isEmpty();
        boolean temcpf = !txtCPF.getText().trim().isEmpty();
        boolean temSexo = radioBtnFeminino.isSelected()
                || radioBtnMasculino.isSelected()
                || radioBtnNaoDizer.isSelected();
        boolean temEquipe = comboBoxEquipe.getSelectedIndex() >= 0;

        btnSalvarUsuario.setEnabled(temNome && temEmail && temDtNascimento && temTelefone && temcpf && temEquipe && temSexo);
    }

    private void limparCampos() {
        txtNome.setText("");
        txtCPF.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
        txtDataNascimento.setText("");
        btnGroupSexo.clearSelection();
        comboBoxEquipe.setSelectedIndex(-1);
        btnEditarUsuario.setEnabled(false);
        btnExcluirUsuario.setEnabled(false);
    }

    private void carregarComboEquipes(List<Equipe> listaEquipes) {
        comboBoxEquipe.removeAllItems();

        for (Equipe equipe : listaEquipes) {
            comboBoxEquipe.addItem(equipe);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgJanUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgJanUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgJanUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgJanUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgJanUsuario dialog = new DlgJanUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnExcluirUsuario;
    private javax.swing.ButtonGroup btnGroupSexo;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisarUsuario;
    private javax.swing.JButton btnSalvarUsuario;
    private javax.swing.JButton btnVoltarUsuario;
    private javax.swing.JComboBox<Object> comboBoxEquipe;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelDataNascimento;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNomeUsuario;
    private javax.swing.JLabel labelSetor;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JPanel painelTituloUsuario;
    private javax.swing.JPanel panelSexo;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JRadioButton radioBtnFeminino;
    private javax.swing.JRadioButton radioBtnMasculino;
    private javax.swing.JRadioButton radioBtnNaoDizer;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JLabel txtDesc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
