package view;

import controller.FuncoesUteis;
import static controller.FuncoesUteis.strToDate;
import controller.GerenciadorInterface;
import domain.Equipe;
import domain.Usuario;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Karoliny
 */
public class DlgJanUsuario extends javax.swing.JDialog {

    private Usuario usuarioSelecionado;

    public DlgJanUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        try {
            List<Equipe> lista = GerenciadorInterface.getMyInstance().getDominio().listarEquipes();
            carregarComboEquipes(lista);

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao carregar equipes");
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar classe");
        }

        btnSalvarUsuario.setEnabled(false);
        btnEditarUsuario.setEnabled(false);
        btnExcluirUsuario.setEnabled(false);

        txtNome.addActionListener(e -> verificarCampos());
        txtEmail.addActionListener(e -> verificarCampos());
        txtDataNascimento.addActionListener(e -> verificarCampos());
        txtCPF.addActionListener(e -> verificarCampos());
        txtTelefone.addActionListener(e -> verificarCampos());
        comboBoxEquipe.addActionListener(e -> verificarCampos());
        radioBtnFeminino.addActionListener(e -> verificarCampos());
        radioBtnMasculino.addActionListener(e -> verificarCampos());
        radioBtnNaoDizer.addActionListener(e -> verificarCampos());
        txtSenha.addActionListener(e -> verificarCampos());
        txtConfSenha.addActionListener(e -> verificarCampos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSexo = new javax.swing.ButtonGroup();
        painelTituloUsuario = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        txtDesc = new javax.swing.JLabel();
        panelUsuario = new javax.swing.JPanel();
        labelNomeUsuario = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        panelSexo = new javax.swing.JPanel();
        radioBtnFeminino = new javax.swing.JRadioButton();
        radioBtnMasculino = new javax.swing.JRadioButton();
        radioBtnNaoDizer = new javax.swing.JRadioButton();
        labelEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        labelDataNascimento = new javax.swing.JLabel();
        panelSenha = new javax.swing.JPanel();
        labelSenha = new javax.swing.JLabel();
        labelConfSenha = new javax.swing.JLabel();
        txtConfSenha = new javax.swing.JPasswordField();
        txtSenha = new javax.swing.JPasswordField();
        labelTelefone = new javax.swing.JLabel();
        labelSetor = new javax.swing.JLabel();
        comboBoxEquipe = new javax.swing.JComboBox<>();
        btnSalvarUsuario = new javax.swing.JButton();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        labelCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        btnPesquisarUsuario = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnExcluirUsuario = new javax.swing.JButton();
        btnVoltarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtTitulo.setFont(new java.awt.Font("Source Sans Pro Black", 0, 24)); // NOI18N
        txtTitulo.setText("Usuários");

        txtDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDesc.setText("Cadastro de usuários");

        javax.swing.GroupLayout painelTituloUsuarioLayout = new javax.swing.GroupLayout(painelTituloUsuario);
        painelTituloUsuario.setLayout(painelTituloUsuarioLayout);
        painelTituloUsuarioLayout.setHorizontalGroup(
            painelTituloUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloUsuarioLayout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addGroup(painelTituloUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTituloUsuarioLayout.createSequentialGroup()
                        .addComponent(txtTitulo)
                        .addGap(197, 197, 197))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTituloUsuarioLayout.createSequentialGroup()
                        .addComponent(txtDesc)
                        .addGap(180, 180, 180))))
        );
        painelTituloUsuarioLayout.setVerticalGroup(
            painelTituloUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDesc)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelNomeUsuario.setText("Nome");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        panelSexo.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));

        btnGroupSexo.add(radioBtnFeminino);
        radioBtnFeminino.setText("Feminino");

        btnGroupSexo.add(radioBtnMasculino);
        radioBtnMasculino.setText("Masculino");
        radioBtnMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnMasculinoActionPerformed(evt);
            }
        });

        btnGroupSexo.add(radioBtnNaoDizer);
        radioBtnNaoDizer.setText("Prefiro não dizer");
        radioBtnNaoDizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnNaoDizerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSexoLayout = new javax.swing.GroupLayout(panelSexo);
        panelSexo.setLayout(panelSexoLayout);
        panelSexoLayout.setHorizontalGroup(
            panelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSexoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioBtnFeminino)
                    .addComponent(radioBtnMasculino)
                    .addComponent(radioBtnNaoDizer))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelSexoLayout.setVerticalGroup(
            panelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSexoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioBtnFeminino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBtnMasculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBtnNaoDizer)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        labelEmail.setText("E-mail");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        labelDataNascimento.setText("Data de nascimento");

        panelSenha.setBorder(javax.swing.BorderFactory.createTitledBorder("Definição de senha"));

        labelSenha.setText("Senha");

        labelConfSenha.setText("Confirmação de senha");

        javax.swing.GroupLayout panelSenhaLayout = new javax.swing.GroupLayout(panelSenha);
        panelSenha.setLayout(panelSenhaLayout);
        panelSenhaLayout.setHorizontalGroup(
            panelSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSenhaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSenha))
                .addGap(18, 18, 18)
                .addGroup(panelSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelConfSenha))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        panelSenhaLayout.setVerticalGroup(
            panelSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSenhaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenha)
                    .addComponent(labelConfSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelTelefone.setText("Telefone");

        labelSetor.setText("Equipe");

        comboBoxEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEquipeActionPerformed(evt);
            }
        });

        btnSalvarUsuario.setText("Salvar");
        btnSalvarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarUsuarioActionPerformed(evt);
            }
        });

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        labelCPF.setText("CPF");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnPesquisarUsuario.setText("Pesquisar");
        btnPesquisarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarUsuarioActionPerformed(evt);
            }
        });

        btnEditarUsuario.setText("Editar");
        btnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnExcluirUsuario.setText("Excluir");
        btnExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNomeUsuario)
                    .addComponent(labelEmail)
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addComponent(labelDataNascimento)
                        .addGap(44, 44, 44)
                        .addComponent(labelTelefone))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                        .addComponent(txtNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarUsuario))
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addComponent(txtDataNascimento, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(labelCPF))
                        .addGap(18, 18, 18)
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSetor)
                            .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comboBoxEquipe, javax.swing.GroupLayout.Alignment.LEADING, 0, 137, Short.MAX_VALUE)
                                .addComponent(txtTelefone))))
                    .addComponent(txtEmail))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                        .addComponent(panelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalvarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102))))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addComponent(labelNomeUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDataNascimento)
                            .addComponent(labelTelefone))))
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCPF)
                            .addComponent(labelSetor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(panelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnSalvarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluirUsuario)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnVoltarUsuario.setText("<< Voltar");
        btnVoltarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVoltarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(painelTituloUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(painelTituloUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVoltarUsuario)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarUsuarioActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarUsuarioActionPerformed

    private void radioBtnMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnMasculinoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void radioBtnNaoDizerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnNaoDizerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnNaoDizerActionPerformed

    private void btnSalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarUsuarioActionPerformed
        try {
            Usuario usuario = new Usuario();

            usuario.setNome(txtNome.getText());
            usuario.setCpf(txtCPF.getText());
            usuario.setEmail(txtEmail.getText());
            String sexo = null;

            if (radioBtnFeminino.isSelected()) {
                sexo = "F";
            } else if (radioBtnMasculino.isSelected()) {
                sexo = "M";
            } else if (radioBtnNaoDizer.isSelected()) {
                sexo = "ND";
            }
            usuario.setSexo(sexo);
            usuario.setTelefone(txtTelefone.getText());

            String senha = new String(txtSenha.getPassword());
            String confSenha = new String(txtConfSenha.getPassword());

            if (!senha.equals(confSenha)) {
                JOptionPane.showMessageDialog(null, "As senhas não coincidem!");
            } else {
                usuario.setSenha(txtSenha.getText());
            }

            usuario.setDtNascimento(strToDate(txtDataNascimento.getText()));

            Equipe equipe = (Equipe) comboBoxEquipe.getSelectedItem();
            usuario.setEquipe(equipe);

            GerenciadorInterface.getMyInstance().getDominio().inserirUsuario(usuario);

            JOptionPane.showMessageDialog(null, "Usuário salvo com sucesso!");
            limparCampos();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao salvar usuário");
        }
    }//GEN-LAST:event_btnSalvarUsuarioActionPerformed

    private void comboBoxEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxEquipeActionPerformed

    private void btnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuarioActionPerformed
        try {
            Usuario usuario = usuarioSelecionado;

            usuario.setNome(txtNome.getText());
            usuario.setCpf(txtCPF.getText());
            usuario.setEmail(txtEmail.getText());
            String sexo = null;

            if (radioBtnFeminino.isSelected()) {
                sexo = "F";
            } else if (radioBtnMasculino.isSelected()) {
                sexo = "M";
            } else if (radioBtnNaoDizer.isSelected()) {
                sexo = "ND";
            }
            usuario.setSexo(sexo);
            usuario.setTelefone(txtTelefone.getText());
            usuario.setDtNascimento(strToDate(txtDataNascimento.getText()));

            Equipe equipe = (Equipe) comboBoxEquipe.getSelectedItem();
            usuario.setEquipe(equipe);

            GerenciadorInterface.getMyInstance().getDominio().alterarUsuario(usuario);

            JOptionPane.showMessageDialog(null, "Usuário editado com sucesso!");
            limparCampos();
            btnEditarUsuario.setEnabled(false);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao editar usuário");
        }
    }//GEN-LAST:event_btnEditarUsuarioActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPesquisarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarUsuarioActionPerformed
        try {

            String nomeConf = txtNome.getText().trim();

            if (nomeConf.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Digite um nome!");
                return;
            }

            if (!nomeConf.matches("[a-zA-ZÀ-ÿ ]+")) {
                JOptionPane.showMessageDialog(null, "Nome inválido! Digite apenas letras.");
                return;
            }

            btnExcluirUsuario.setEnabled(true);
            btnEditarUsuario.setEnabled(true);
            String nome = txtNome.getText();

            List<Usuario> lista = GerenciadorInterface.getMyInstance().getDominio().pesquisarUsuario(nome);

            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Usuário não encontrado!");
                return;
            }

            usuarioSelecionado = lista.get(0);
            preencherCampos(usuarioSelecionado);
            btnSalvarUsuario.setEnabled(false);
            btnEditarUsuario.setEnabled(true);

            txtSenha.setEnabled(false);
            txtConfSenha.setEnabled(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar: " + e.getMessage());
        }

    }//GEN-LAST:event_btnPesquisarUsuarioActionPerformed

    private void btnExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUsuarioActionPerformed
        try {
            int resposta = JOptionPane.showConfirmDialog(
                    null,
                    "Deseja realmente excluir este usuário?",
                    "Confirmação",
                    JOptionPane.YES_NO_OPTION
            );

            if (resposta == JOptionPane.YES_OPTION) {

                GerenciadorInterface.getMyInstance().getDominio().excluirUsuario(usuarioSelecionado.getId());

                JOptionPane.showMessageDialog(null, "Usuário excluído com sucesso!");

                limparCampos();
                usuarioSelecionado = null;

                btnEditarUsuario.setEnabled(false);
                btnSalvarUsuario.setEnabled(false);
                btnExcluirUsuario.setEnabled(false);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir: " + e.getMessage());
        }
    }//GEN-LAST:event_btnExcluirUsuarioActionPerformed

    private void verificarCampos() {
        boolean temNome = !txtNome.getText().trim().isEmpty();
        boolean temEmail = !txtEmail.getText().trim().isEmpty();
        boolean temDtNascimento = !txtDataNascimento.getText().trim().isEmpty();
        boolean temTelefone = !txtTelefone.getText().trim().isEmpty();
        boolean temcpf = !txtCPF.getText().trim().isEmpty();

        String senha = new String(txtSenha.getPassword());
        String confSenha = new String(txtConfSenha.getPassword());

        boolean temSenha = !senha.isEmpty();
        boolean temConfSenha = !confSenha.isEmpty();
        boolean senhasIguais = senha.equals(confSenha);

        boolean temSexo = radioBtnFeminino.isSelected()
                || radioBtnMasculino.isSelected()
                || radioBtnNaoDizer.isSelected();
        boolean temEquipe = comboBoxEquipe.getSelectedIndex() > 0;

        btnSalvarUsuario.setEnabled(temNome && temEmail && temDtNascimento && temTelefone && temcpf && temSenha && temConfSenha && temEquipe && temSexo && senhasIguais);
    }

    private void limparCampos() {
        txtNome.setText("");
        txtCPF.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
        txtSenha.setText("");
        txtConfSenha.setText("");
        txtDataNascimento.setText("");
        btnGroupSexo.clearSelection();
        comboBoxEquipe.setSelectedIndex(-1);

        txtSenha.setEnabled(true);
        txtConfSenha.setEnabled(true);
        btnEditarUsuario.setEnabled(false);
        btnExcluirUsuario.setEnabled(false);
    }

    private void carregarComboEquipes(List<Equipe> listaEquipes) {
        comboBoxEquipe.removeAllItems();

        for (Equipe equipe : listaEquipes) {
            comboBoxEquipe.addItem(equipe);
        }
    }

    private void preencherCampos(Usuario usuario) {

        txtNome.setText(usuario.getNome());
        txtEmail.setText(usuario.getEmail());
        txtCPF.setText(usuario.getCpf());
        txtTelefone.setText(usuario.getTelefone());

        try {
            txtDataNascimento.setText(FuncoesUteis.dateToStr(usuario.getDtNascimento()));
        } catch (Exception e) {
            e.printStackTrace();
        }

        switch (usuario.getSexo()) {
            case "F":
                radioBtnFeminino.setSelected(true);
                break;
            case "M":
                radioBtnMasculino.setSelected(true);
                break;
            default:
                radioBtnNaoDizer.setSelected(true);
        }

        comboBoxEquipe.setSelectedItem(usuario.getEquipe());
//        txtSenha.setText(usuario.getSenha());
//        txtConfSenha.setText(usuario.getSenha());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgJanUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgJanUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgJanUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgJanUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgJanUsuario dialog = new DlgJanUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnExcluirUsuario;
    private javax.swing.ButtonGroup btnGroupSexo;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisarUsuario;
    private javax.swing.JButton btnSalvarUsuario;
    private javax.swing.JButton btnVoltarUsuario;
    private javax.swing.JComboBox<Object> comboBoxEquipe;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelConfSenha;
    private javax.swing.JLabel labelDataNascimento;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNomeUsuario;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelSetor;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JPanel painelTituloUsuario;
    private javax.swing.JPanel panelSenha;
    private javax.swing.JPanel panelSexo;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JRadioButton radioBtnFeminino;
    private javax.swing.JRadioButton radioBtnMasculino;
    private javax.swing.JRadioButton radioBtnNaoDizer;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JPasswordField txtConfSenha;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JLabel txtDesc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
