/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package windows;

/**
 *
 * @author Karoliny
 */
public class FrmJanEquipe extends javax.swing.JDialog {

    /**
     * Creates new form FrmEquipe
     */
    public FrmJanEquipe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTituloEquipe = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        txtDesc = new javax.swing.JLabel();
        paneCadEquipe = new javax.swing.JTabbedPane();
        paneCadastrarEquipe = new javax.swing.JPanel();
        labelNomeEquipe = new javax.swing.JLabel();
        txtNomeEquipe = new javax.swing.JTextField();
        labelDescricaoEquipe = new javax.swing.JLabel();
        txtFieldDescricao = new javax.swing.JTextField();
        labelLider = new javax.swing.JLabel();
        comboBoxLider = new javax.swing.JComboBox<>();
        panelMembros = new javax.swing.JPanel();
        checkBox1 = new javax.swing.JCheckBox();
        checkBox2 = new javax.swing.JCheckBox();
        checkBox3 = new javax.swing.JCheckBox();
        checkBox4 = new javax.swing.JCheckBox();
        checkBox5 = new javax.swing.JCheckBox();
        checkBox6 = new javax.swing.JCheckBox();
        labelMembros = new javax.swing.JLabel();
        btnSalvarEquipe = new javax.swing.JButton();
        labelSetor = new javax.swing.JLabel();
        comboBoxSetor = new javax.swing.JComboBox<>();
        paneListarEquipe = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tableEquipe = new javax.swing.JTable();
        btnEditarEquipe = new javax.swing.JButton();
        btnExcluirEquipe = new javax.swing.JButton();
        btnVoltarJanEquipe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FocusTask - Equipes");
        setPreferredSize(new java.awt.Dimension(590, 585));

        txtTitulo.setFont(new java.awt.Font("Source Sans Pro Black", 0, 24)); // NOI18N
        txtTitulo.setText("Equipes");

        txtDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDesc.setText("Cadastro, edição, exclusão e listagem");

        javax.swing.GroupLayout painelTituloEquipeLayout = new javax.swing.GroupLayout(painelTituloEquipe);
        painelTituloEquipe.setLayout(painelTituloEquipeLayout);
        painelTituloEquipeLayout.setHorizontalGroup(
            painelTituloEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTituloEquipeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTitulo)
                .addGap(197, 197, 197))
            .addGroup(painelTituloEquipeLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(txtDesc)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        painelTituloEquipeLayout.setVerticalGroup(
            painelTituloEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloEquipeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDesc)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        paneCadastrarEquipe.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelNomeEquipe.setText("Nome da equipe");

        txtNomeEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEquipeActionPerformed(evt);
            }
        });

        labelDescricaoEquipe.setText("Descrição");

        labelLider.setText("Líder");

        comboBoxLider.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "              ", "Luisa", "Felipe", "Camila", "Paula", "Lucas" }));

        panelMembros.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        checkBox1.setText("Luisa");
        checkBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox1ActionPerformed(evt);
            }
        });

        checkBox2.setText("Felipe");
        checkBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox2ActionPerformed(evt);
            }
        });

        checkBox3.setText("Camila");
        checkBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox3ActionPerformed(evt);
            }
        });

        checkBox4.setText("Paula");
        checkBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox4ActionPerformed(evt);
            }
        });

        checkBox5.setText("Lucas");

        checkBox6.setText("Andre");

        javax.swing.GroupLayout panelMembrosLayout = new javax.swing.GroupLayout(panelMembros);
        panelMembros.setLayout(panelMembrosLayout);
        panelMembrosLayout.setHorizontalGroup(
            panelMembrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMembrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMembrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBox1)
                    .addComponent(checkBox2)
                    .addComponent(checkBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(panelMembrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBox4)
                    .addComponent(checkBox5)
                    .addComponent(checkBox6))
                .addGap(22, 22, 22))
        );
        panelMembrosLayout.setVerticalGroup(
            panelMembrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMembrosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelMembrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBox1)
                    .addComponent(checkBox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMembrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBox2)
                    .addComponent(checkBox5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMembrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBox3)
                    .addComponent(checkBox6))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        labelMembros.setText("Membros");

        btnSalvarEquipe.setText("Salvar");

        labelSetor.setText("Setor");

        comboBoxSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "           ", "Marketing", "Comunicação", "T.I." }));

        javax.swing.GroupLayout paneCadastrarEquipeLayout = new javax.swing.GroupLayout(paneCadastrarEquipe);
        paneCadastrarEquipe.setLayout(paneCadastrarEquipeLayout);
        paneCadastrarEquipeLayout.setHorizontalGroup(
            paneCadastrarEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCadastrarEquipeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(paneCadastrarEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelDescricaoEquipe)
                    .addComponent(txtNomeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldDescricao)
                    .addComponent(labelNomeEquipe)
                    .addComponent(btnSalvarEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSetor)
                    .addComponent(comboBoxSetor, 0, 204, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(paneCadastrarEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxLider, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLider)
                    .addComponent(labelMembros)
                    .addComponent(panelMembros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        paneCadastrarEquipeLayout.setVerticalGroup(
            paneCadastrarEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCadastrarEquipeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(paneCadastrarEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeEquipe)
                    .addComponent(labelLider))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastrarEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxLider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneCadastrarEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescricaoEquipe)
                    .addComponent(labelMembros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastrarEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCadastrarEquipeLayout.createSequentialGroup()
                        .addComponent(panelMembros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paneCadastrarEquipeLayout.createSequentialGroup()
                        .addComponent(txtFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelSetor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btnSalvarEquipe)
                        .addGap(16, 16, 16))))
        );

        paneCadEquipe.addTab("Cadastrar Equipes", paneCadastrarEquipe);

        paneListarEquipe.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableEquipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Equipe", "Líder", "Setor"
            }
        ));
        jScrollPane9.setViewportView(tableEquipe);

        btnEditarEquipe.setText("Editar");

        btnExcluirEquipe.setText("Excluir");

        javax.swing.GroupLayout paneListarEquipeLayout = new javax.swing.GroupLayout(paneListarEquipe);
        paneListarEquipe.setLayout(paneListarEquipeLayout);
        paneListarEquipeLayout.setHorizontalGroup(
            paneListarEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneListarEquipeLayout.createSequentialGroup()
                .addContainerGap(316, Short.MAX_VALUE)
                .addComponent(btnEditarEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(paneListarEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneListarEquipeLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        paneListarEquipeLayout.setVerticalGroup(
            paneListarEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneListarEquipeLayout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addGroup(paneListarEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarEquipe)
                    .addComponent(btnExcluirEquipe))
                .addGap(15, 15, 15))
            .addGroup(paneListarEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneListarEquipeLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        paneCadEquipe.addTab("Listar Equipes", paneListarEquipe);

        btnVoltarJanEquipe.setText("<< Voltar");
        btnVoltarJanEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarJanEquipeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVoltarJanEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneCadEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(painelTituloEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTituloEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(paneCadEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVoltarJanEquipe)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarJanEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarJanEquipeActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarJanEquipeActionPerformed

    private void txtNomeEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEquipeActionPerformed

    private void checkBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox1ActionPerformed

    private void checkBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox2ActionPerformed

    private void checkBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox3ActionPerformed

    private void checkBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJanEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJanEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJanEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJanEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmJanEquipe dialog = new FrmJanEquipe(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarEquipe;
    private javax.swing.JButton btnExcluirEquipe;
    private javax.swing.JButton btnSalvarEquipe;
    private javax.swing.JButton btnVoltarJanEquipe;
    private javax.swing.JCheckBox checkBox1;
    private javax.swing.JCheckBox checkBox2;
    private javax.swing.JCheckBox checkBox3;
    private javax.swing.JCheckBox checkBox4;
    private javax.swing.JCheckBox checkBox5;
    private javax.swing.JCheckBox checkBox6;
    private javax.swing.JComboBox<String> comboBoxLider;
    private javax.swing.JComboBox<String> comboBoxSetor;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel labelDescricaoEquipe;
    private javax.swing.JLabel labelLider;
    private javax.swing.JLabel labelMembros;
    private javax.swing.JLabel labelNomeEquipe;
    private javax.swing.JLabel labelSetor;
    private javax.swing.JPanel painelTituloEquipe;
    private javax.swing.JTabbedPane paneCadEquipe;
    private javax.swing.JPanel paneCadastrarEquipe;
    private javax.swing.JPanel paneListarEquipe;
    private javax.swing.JPanel panelMembros;
    private javax.swing.JTable tableEquipe;
    private javax.swing.JLabel txtDesc;
    private javax.swing.JTextField txtFieldDescricao;
    private javax.swing.JTextField txtNomeEquipe;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
